# Información del proyecto

## Propuesta inicial

En un contexto donde plataformas como Spotify o YouTube concentran gran parte del consumo musical, los artistas independientes enfrentan desafíos relacionados con la transparencia en los ingresos, la detección de usos no autorizados de su obra y la optimización de sus estrategias de lanzamiento. Este proyecto propone abordar estas problemáticas mediante el desarrollo de tres módulos principales basados en datos existentes. Los módulos son:

1. Análisis de mercado musical, orientado a identificar patrones de consumo, tendencias por género y oportunidades de monetización para artistas, permitiendo generar recomendaciones estratégicas basadas en datos (por ejemplo, mercados potenciales o características musicales asociadas al éxito).

2. Detección de fraude en streams, mediante técnicas de análisis de comportamiento y modelos de detección de anomalías, con el fin de identificar reproducciones artificiales o manipuladas que afectan la distribución justa de royalties.

3. Detector de copyright basado en inteligencia artificial, capaz de identificar la presencia de contenido musical en diferentes plataformas digitales mediante técnicas de procesamiento de audio, como espectrogramas y huellas digitales (audio fingerprinting), inspirado en tecnologías utilizadas por empresas como Shazam.

## Información de los módulos:


**1. Analisis del mercado musical apra el artista:**

* Datos posibles: Streams por país, Género musical, Playlist placement, TikTok trends, Crecimiento de artistas similares...

* Análisis (EDA): crecimiento por género, países con más crecimiento, correlación entre playlist y streams, horas/días con más reproducciones

* ML posible: Predicción de streams de una canción, Predicción de viralidad, 
* Modelos: Random Forest, XGBoost, LSTM para series temporales

* Output en tu plataforma

“Tu canción tiene 65% probabilidad de viralizarse en México”, “Este beat funciona mejor en playlist de chill trap”

* EXTRA DATOS: EDAD DE LA AUDIENCIA PARA AVERIGUAR TARGET SEGÚN PLATAFORMA. (MÉTRICAS AUDIENCIA TIK TOK)

**2. Fraude en streams:**

* Variables generales para objetivo 2:

| Variable                 | Tipo de dato | Para qué sirve                    | Ejemplo          |
| ------------------------ | ------------ | --------------------------------- | ---------------- |
| user_id                  | categorical  | identificar usuarios únicos       | U10233           |
| track_id                 | categorical  | identificar canción               | TRK8891          |
| session_id               | categorical  | identificar sesión                | S78123           |
| timestamp                | datetime     | detectar patrones temporales      | 2025-03-20 03:10 |
| listen_duration          | float        | detectar streams muy cortos       | 8.2 sec          |
| track_length             | float        | comparar duración real            | 180 sec          |
| completion_rate          | float        | ratio escucha completa            | 0.05             |
| device_type              | categorical  | bots usan dispositivos repetidos  | mobile / desktop |
| country                  | categorical  | detectar granjas de streams       | IN, RU           |
| playlist_source          | categorical  | detectar playlists sospechosas    | algorithmic      |
| repeat_count             | integer      | repeticiones consecutivas         | 25               |
| unique_tracks_in_session | integer      | bots suelen repetir pocas         | 1                |
| skip_rate                | float        | detectar skip masivo              | 0.90             |
| time_between_streams     | float        | bots tienen intervalos constantes | 5 sec            |


* Variables para futures engineering:

| Feature          | Fórmula                 |
| ---------------- | ----------------------- |
| repeat_ratio     | repeats / total streams |
| avg_listen_time  | mean(listen_duration)   |
| stream_frequency | streams / hour          |
| session_entropy  | diversidad de canciones |
| country_entropy  | diversidad geográfica   |


**3. Detector de copyright usando IA (Music Information Retrieval (MIR)):**

* Sistemas comerciales como Shazam usan huellas acústicas para identificar canciones.


* Modelo ML: con CNN usar como si fuera una imagen. 
* Al tratar info como imagen del sonido los ejes son: X = tiempo, Y = frecuencia y Color = energía.
* Variables generales para el punto 3: 

| Variable         | Tipo         | Para qué sirve                  | Ejemplo   |
| ---------------- | ------------ | ------------------------------- | --------- |
| track_id         | categorical  | identificar canción             | T123      |
| audio_file       | binary/audio | audio original                  | .wav      |
| sampling_rate    | int          | frecuencia audio                | 44100     |
| duration         | float        | duración track                  | 180s      |
| spectrogram      | matrix       | representación visual del audio | array     |
| mfcc_features    | vector       | características del timbre      | [12 dims] |
| chroma_features  | vector       | notas musicales                 | [12 dims] |
| tempo            | float        | BPM                             | 95        |
| pitch            | float        | tonalidad                       | C minor   |
| fingerprint_hash | hash         | huella digital del audio        | a9f12e    |


* Variables / Futures usadas en sonido:

| Feature            | Qué mide          |
| ------------------ | ----------------- |
| MFCC               | timbre del sonido |
| chroma             | notas musicales   |
| spectral centroid  | brillo del sonido |
| tempo              | BPM               |
| zero crossing rate | ruido             |

## Objetivos del proyecto


* Desarrollar un sistema de análisis de datos que permita comprender el comportamiento del mercado musical digital.

* Implementar modelos de machine learning para predecir el rendimiento de canciones y recomendar estrategias de monetización.

* Diseñar un sistema de detección de anomalías aplicado a datos de streaming para identificar posibles fraudes.

* Construir un prototipo de reconocimiento de audio para la identificación de contenido protegido por derechos de autor.

* Integrar estos componentes en una arquitectura escalable que pueda evolucionar hacia una plataforma real.

## Hipótesis de trabajo


* Es posible predecir el éxito relativo de una canción a partir de variables como sus características de audio, contexto de lanzamiento y métricas de engagement.

* Los patrones de fraude en streaming pueden ser identificados mediante comportamientos anómalos en los datos de escucha, sin necesidad de información sensible como direcciones IP.

* Las técnicas de procesamiento de audio permiten detectar coincidencias entre contenidos musicales con un alto grado de precisión, incluso en entornos ruidosos o transformados.

* El uso combinado de análisis de datos e inteligencia artificial puede ayudar a los artistas independientes a optimizar sus ingresos y tomar decisiones estratégicas más informadas.

# Data encontrada:

## **1. Analisis del mercado musical apra el artista:**

Se usan los datos de Last.fm API ya que  se basan en consumo real de usuarios.

### Imports

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests

### API Request

In [4]:
ret = requests.get(f"https://ws.audioscrobbler.com/2.0/?method=chart.gettoptracks&api_key=63e059c3c912a3f642daf2372484d183&format=json")
ret.json()

{'tracks': {'track': [{'name': 'Stateside + Zara Larsson',
    'duration': '176',
    'playcount': '13739893',
    'listeners': '967585',
    'mbid': 'ffbf7862-2476-4164-ac32-f5904ccefe0f',
    'url': 'https://www.last.fm/music/PinkPantheress/_/Stateside+%252B+Zara+Larsson',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'PinkPantheress',
     'mbid': '7441014f-f8f5-494f-81db-ff166fbc078d',
     'url': 'https://www.last.fm/music/PinkPantheress'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'American Girls',
    'duration': '213',
    'playcount': '1729748',
    'listeners': '350474',
    'mbid': '2c85fe70-3c0e-4b43-8d97-f5b5c4757f3a',
    'url': 'https://www.last.fm/music/Harry+Styles/_/American+Girls',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Harry Styles',
     'mbid': '7eb1ce54-a355-41f9-8d68-e018b096d427',
     'url': 'https://www.last.fm/music/Harry+Styles'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'Taste Back',
    'duration': '221',
    'playcount': '1463030',
    'listeners': '280270',
    'mbid': '49562fdd-c325-415a-a2be-7d71f121b25d',
    'url': 'https://www.last.fm/music/Harry+Styles/_/Taste+Back',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Harry Styles',
     'mbid': '7eb1ce54-a355-41f9-8d68-e018b096d427',
     'url': 'https://www.last.fm/music/Harry+Styles'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'Ready, Steady, Go!',
    'duration': '160',
    'playcount': '1458007',
    'listeners': '289586',
    'mbid': '4f255861-925f-4629-ab41-22f4b35d8585',
    'url': 'https://www.last.fm/music/Harry+Styles/_/Ready,+Steady,+Go%21',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Harry Styles',
     'mbid': '7eb1ce54-a355-41f9-8d68-e018b096d427',
     'url': 'https://www.last.fm/music/Harry+Styles'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'Fame Is a Gun',
    'duration': '183',
    'playcount': '18090157',
    'listeners': '969791',
    'mbid': '37907edc-06c1-4d08-b2ef-7e5221986f91',
    'url': 'https://www.last.fm/music/Addison+Rae/_/Fame+Is+a+Gun',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Addison Rae',
     'mbid': '610b71d9-fa78-47d6-9073-083922e73840',
     'url': 'https://www.last.fm/music/Addison+Rae'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'Aperture',
    'duration': '311',
    'playcount': '4674521',
    'listeners': '541196',
    'mbid': '2b1c66e1-4023-4294-813a-9d7d921bffbc',
    'url': 'https://www.last.fm/music/Harry+Styles/_/Aperture',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Harry Styles',
     'mbid': '7eb1ce54-a355-41f9-8d68-e018b096d427',
     'url': 'https://www.last.fm/music/Harry+Styles'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'Babydoll',
    'duration': '97',
    'playcount': '21490256',
    'listeners': '1447813',
    'mbid': 'c6fa2cd4-a100-4db8-8206-3cbcdd3aabe0',
    'url': 'https://www.last.fm/music/Dominic+Fike/_/Babydoll',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Dominic Fike',
     'mbid': 'e337c918-098f-418e-97a2-81dc224b1bf9',
     'url': 'https://www.last.fm/music/Dominic+Fike'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'Coming Up Roses',
    'duration': '248',
    'playcount': '1320572',
    'listeners': '260479',
    'mbid': '765c4880-c4b2-4958-8a09-59feba72d3ea',
    'url': 'https://www.last.fm/music/Harry+Styles/_/Coming+Up+Roses',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Harry Styles',
     'mbid': '7eb1ce54-a355-41f9-8d68-e018b096d427',
     'url': 'https://www.last.fm/music/Harry+Styles'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'Midnight Sun',
    'duration': '189',
    'playcount': '10302086',
    'listeners': '635786',
    'mbid': '21e8a4db-0892-428d-a143-0e2215dddbfa',
    'url': 'https://www.last.fm/music/Zara+Larsson/_/Midnight+Sun',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Zara Larsson',
     'mbid': '134e6410-6954-45d1-bd4a-0f2d2ad5471d',
     'url': 'https://www.last.fm/music/Zara+Larsson'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'Are you listening yet?',
    'duration': '192',
    'playcount': '1281023',
    'listeners': '265197',
    'mbid': 'b009d3d9-5ce3-4fdb-b464-7262f3a7ab62',
    'url': 'https://www.last.fm/music/Harry+Styles/_/Are+you+listening+yet%3F',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Harry Styles',
     'mbid': '7eb1ce54-a355-41f9-8d68-e018b096d427',
     'url': 'https://www.last.fm/music/Harry+Styles'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'POP',
    'duration': '216',
    'playcount': '1338557',
    'listeners': '244454',
    'mbid': 'ce5f14fd-c2fa-46d3-a726-3edab60ab899',
    'url': 'https://www.last.fm/music/Harry+Styles/_/POP',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Harry Styles',
     'mbid': '7eb1ce54-a355-41f9-8d68-e018b096d427',
     'url': 'https://www.last.fm/music/Harry+Styles'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'Dracula',
    'duration': '205',
    'playcount': '8821424',
    'listeners': '916413',
    'mbid': '5b1c893a-16da-4e3d-b9b7-6cc57afc360c',
    'url': 'https://www.last.fm/music/Tame+Impala/_/Dracula',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Tame Impala',
     'mbid': '63aa26c3-d59b-4da4-84ac-716b54f1ef4d',
     'url': 'https://www.last.fm/music/Tame+Impala'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'DtMF',
    'duration': '237',
    'playcount': '15327734',
    'listeners': '1227214',
    'mbid': '2944ab9d-2e49-4143-83fb-4e8499469654',
    'url': 'https://www.last.fm/music/Bad+Bunny/_/DtMF',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Bad Bunny',
     'mbid': '89aa5ecb-59ad-46f5-b3eb-2d424e941f19',
     'url': 'https://www.last.fm/music/Bad+Bunny'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'The Waiting Game',
    'duration': '169',
    'playcount': '1196810',
    'listeners': '255036',
    'mbid': '5943585e-421c-449e-8f19-10a2f5740260',
    'url': 'https://www.last.fm/music/Harry+Styles/_/The+Waiting+Game',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Harry Styles',
     'mbid': '7eb1ce54-a355-41f9-8d68-e018b096d427',
     'url': 'https://www.last.fm/music/Harry+Styles'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'Manchild',
    'duration': '213',
    'playcount': '22621692',
    'listeners': '1184919',
    'mbid': '16afd537-24ce-45f4-b3bc-e2ac99de3bf0',
    'url': 'https://www.last.fm/music/Sabrina+Carpenter/_/Manchild',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Sabrina Carpenter',
     'mbid': '1882fe91-cdd9-49c9-9956-8e06a3810bd4',
     'url': 'https://www.last.fm/music/Sabrina+Carpenter'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'End of Beginning',
    'duration': '159',
    'playcount': '33007198',
    'listeners': '1952923',
    'mbid': '298a594f-d201-41c3-a9a6-9e362d5c5c03',
    'url': 'https://www.last.fm/music/Djo/_/End+of+Beginning',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Djo',
     'mbid': '83cedfd0-a118-48eb-ad71-72f4c2f95fd2',
     'url': 'https://www.last.fm/music/Djo'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'Season 2 Weight Loss',
    'duration': '229',
    'playcount': '1207760',
    'listeners': '241233',
    'mbid': '6973ce7c-9fa0-43b4-a707-c7e3d3c47c7a',
    'url': 'https://www.last.fm/music/Harry+Styles/_/Season+2+Weight+Loss',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Harry Styles',
     'mbid': '7eb1ce54-a355-41f9-8d68-e018b096d427',
     'url': 'https://www.last.fm/music/Harry+Styles'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'Dance No More',
    'duration': '194',
    'playcount': '1171848',
    'listeners': '229039',
    'mbid': '29455c07-743a-4511-9ba5-582f1112b0f1',
    'url': 'https://www.last.fm/music/Harry+Styles/_/Dance+No+More',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Harry Styles',
     'mbid': '7eb1ce54-a355-41f9-8d68-e018b096d427',
     'url': 'https://www.last.fm/music/Harry+Styles'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'Good Luck, Babe!',
    'duration': '218',
    'playcount': '58379720',
    'listeners': '2041406',
    'mbid': '1469986c-a292-4d2c-a253-89ed5dc56bf2',
    'url': 'https://www.last.fm/music/Chappell+Roan/_/Good+Luck,+Babe%21',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Chappell Roan',
     'mbid': '56a55378-f155-48de-80a5-d80104221267',
     'url': 'https://www.last.fm/music/Chappell+Roan'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'The Less I Know the Better',
    'duration': '234',
    'playcount': '46908370',
    'listeners': '2699826',
    'mbid': '0409caa8-c467-4455-8033-05ff8d9345f1',
    'url': 'https://www.last.fm/music/Tame+Impala/_/The+Less+I+Know+the+Better',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Tame Impala',
     'mbid': '63aa26c3-d59b-4da4-84ac-716b54f1ef4d',
     'url': 'https://www.last.fm/music/Tame+Impala'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': 'So Easy (To Fall In Love)',
    'duration': '170',
    'playcount': '7441552',
    'listeners': '801518',
    'url': 'https://www.last.fm/music/Olivia+Dean/_/So+Easy+(To+Fall+In+Love)',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Olivia Dean',
     'mbid': '15e0d608-0869-429b-898d-3d8db3ecedd5',
     'url': 'https://www.last.fm/music/Olivia+Dean'},
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'}]},
   {'name': "Carla's Song",
    'duration': '253',
    'playcount': '1083531',
    'listeners': '218777',
    'mbid': '779003b6-0164-48ff-8c9a-01feccca77ba',
    'url': 'https://www.last.fm/music/Harry+Styles/_/Carla%27s+Song',
    'streamable': {'#text': '0', 'fulltrack': '0'},
    'artist': {'name': 'Harry Styles',
     'mbid': '7eb1ce54-a355-41f9-8d68-e018b096d427',

In [5]:
for track in ret.json()["tracks"]["track"]:
  print(track["name"], ". Duracion:", track["duration"],"minutos")

Stateside + Zara Larsson . Duracion: 176 minutos
American Girls . Duracion: 213 minutos
Taste Back . Duracion: 221 minutos
Ready, Steady, Go! . Duracion: 160 minutos
Fame Is a Gun . Duracion: 183 minutos
Aperture . Duracion: 311 minutos
Babydoll . Duracion: 97 minutos
Coming Up Roses . Duracion: 248 minutos
Midnight Sun . Duracion: 189 minutos
Are you listening yet? . Duracion: 192 minutos
POP . Duracion: 216 minutos
Dracula . Duracion: 205 minutos
DtMF . Duracion: 237 minutos
The Waiting Game . Duracion: 169 minutos
Manchild . Duracion: 213 minutos
End of Beginning . Duracion: 159 minutos
Season 2 Weight Loss . Duracion: 229 minutos
Dance No More . Duracion: 194 minutos
Good Luck, Babe! . Duracion: 218 minutos
The Less I Know the Better . Duracion: 234 minutos
So Easy (To Fall In Love) . Duracion: 170 minutos
Carla's Song . Duracion: 253 minutos
WHERE IS MY HUSBAND! . Duracion: 196 minutos
back to friends . Duracion: 199 minutos
Creep . Duracion: 235 minutos
Paint By Numbers . Duracion: 147 minutos
NUEVAYoL . Duracion: 184 minutos
505 . Duracion: 305 minutos
Feel Good Inc. . Duracion: 236 minutos
No One Noticed . Duracion: 236 minutos
Lush Life . Duracion: 201 minutos
Man I Need . Duracion: 184 minutos
BAILE INoLVIDABLE . Duracion: 368 minutos
Sienna . Duracion: 224 minutos
The Fate of Ophelia . Duracion: 226 minutos
I Thought I Saw Your Face Today . Duracion: 185 minutos
Risk It All . Duracion: 204 minutos
Mr. Brightside . Duracion: 222 minutos
Let Down . Duracion: 337 minutos
Lovers Rock . Duracion: 213 minutos
Iris . Duracion: 289 minutos
Earrings . Duracion: 0 minutos
See You Again (feat. Kali Uchis) . Duracion: 180 minutos
Sweater Weather . Duracion: 240 minutos
Dracula - JENNIE remix . Duracion: 209 minutos
Duvet . Duracion: 203 minutos
Pain . Duracion: 98 minutos
E85 . Duracion: 0 minutos
Dreams - 2004 Remaster . Duracion: 257 minutos
Pink + White . Duracion: 290 minutos

In [6]:
music = pd.DataFrame(ret.json()["tracks"]["track"])
music.head()

,name,duration,playcount,listeners,mbid,url,streamable,artist,image
0,Stateside + Zara Larsson,176,13739893,967585,ffbf7862-2476-4164-ac32-f5904ccefe0f,https://www.last.fm/music/PinkPantheress/_/Sta...,"{'#text': '0', 'fulltrack': '0'}","{'name': 'PinkPantheress', 'mbid': '7441014f-f...",[{'#text': 'https://lastfm.freetls.fastly.net/...
1,American Girls,213,1729748,350474,2c85fe70-3c0e-4b43-8d97-f5b5c4757f3a,https://www.last.fm/music/Harry+Styles/_/Ameri...,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Harry Styles', 'mbid': '7eb1ce54-a35...",[{'#text': 'https://lastfm.freetls.fastly.net/...
2,Taste Back,221,1463030,280270,49562fdd-c325-415a-a2be-7d71f121b25d,https://www.last.fm/music/Harry+Styles/_/Taste...,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Harry Styles', 'mbid': '7eb1ce54-a35...",[{'#text': 'https://lastfm.freetls.fastly.net/...
3,"Ready, Steady, Go!",160,1458007,289586,4f255861-925f-4629-ab41-22f4b35d8585,https://www.last.fm/music/Harry+Styles/_/Ready...,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Harry Styles', 'mbid': '7eb1ce54-a35...",[{'#text': 'https://lastfm.freetls.fastly.net/...
4,Fame Is a Gun,183,18090157,969791,37907edc-06c1-4d08-b2ef-7e5221986f91,https://www.last.fm/music/Addison+Rae/_/Fame+I...,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Addison Rae', 'mbid': '610b71d9-fa78...",[{'#text': 'https://lastfm.freetls.fastly.net/...

In [7]:
# Cleaning the data frame:
music.drop(['mbid', 'image', 'url'],axis=1)

,name,duration,playcount,listeners,streamable,artist
0,Stateside + Zara Larsson,176,13739893,967585,"{'#text': '0', 'fulltrack': '0'}","{'name': 'PinkPantheress', 'mbid': '7441014f-f..."
1,American Girls,213,1729748,350474,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Harry Styles', 'mbid': '7eb1ce54-a35..."
2,Taste Back,221,1463030,280270,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Harry Styles', 'mbid': '7eb1ce54-a35..."
3,"Ready, Steady, Go!",160,1458007,289586,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Harry Styles', 'mbid': '7eb1ce54-a35..."
4,Fame Is a Gun,183,18090157,969791,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Addison Rae', 'mbid': '610b71d9-fa78..."
5,Aperture,311,4674521,541196,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Harry Styles', 'mbid': '7eb1ce54-a35..."
6,Babydoll,97,21490256,1447813,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Dominic Fike', 'mbid': 'e337c918-098..."
7,Coming Up Roses,248,1320572,260479,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Harry Styles', 'mbid': '7eb1ce54-a35..."
8,Midnight Sun,189,10302086,635786,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Zara Larsson', 'mbid': '134e6410-695..."
9,Are you listening yet?,192,1281023,265197,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Harry Styles', 'mbid': '7eb1ce54-a35..."
10,POP,216,1338557,244454,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Harry Styles', 'mbid': '7eb1ce54-a35..."
11,Dracula,205,8821424,916413,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Tame Impala', 'mbid': '63aa26c3-d59b..."
12,DtMF,237,15327734,1227214,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Bad Bunny', 'mbid': '89aa5ecb-59ad-4..."
13,The Waiting Game,169,1196810,255036,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Harry Styles', 'mbid': '7eb1ce54-a35..."
14,Manchild,213,22621692,1184919,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Sabrina Carpenter', 'mbid': '1882fe9..."
15,End of Beginning,159,33007198,1952923,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Djo', 'mbid': '83cedfd0-a118-48eb-ad..."
16,Season 2 Weight Loss,229,1207760,241233,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Harry Styles', 'mbid': '7eb1ce54-a35..."
17,Dance No More,194,1171848,229039,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Harry Styles', 'mbid': '7eb1ce54-a35..."
18,"Good Luck, Babe!",218,58379720,2041406,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Chappell Roan', 'mbid': '56a55378-f1..."
19,The Less I Know the Better,234,46908370,2699826,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Tame Impala', 'mbid': '63aa26c3-d59b..."
20,So Easy (To Fall In Love),170,7441552,801518,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Olivia Dean', 'mbid': '15e0d608-0869..."
21,Carla's Song,253,1083531,218777,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Harry Styles', 'mbid': '7eb1ce54-a35..."
22,WHERE IS MY HUSBAND!,196,9455956,895647,"{'#text': '0', 'fulltrack': '0'}","{'name': 'RAYE', 'mbid': '8be564c3-dfba-440b-a..."
23,back to friends,199,22949634,1358126,"{'#text': '0', 'fulltrack': '0'}","{'name': 'sombr', 'mbid': '502cf908-9921-48bc-..."
24,Creep,235,58761298,4023394,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Radiohead', 'mbid': 'a74b1b7f-71a5-4..."
25,Paint By Numbers,147,940941,217335,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Harry Styles', 'mbid': '7eb1ce54-a35..."
26,NUEVAYoL,184,11716381,971809,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Bad Bunny', 'mbid': '89aa5ecb-59ad-4..."
27,505,305,56462199,2960352,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Arctic Monkeys', 'mbid': 'ada7a83c-e..."
28,Feel Good Inc.,236,38803621,3200051,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Gorillaz', 'mbid': 'e21857d5-3256-45..."
29,No One Noticed,236,31789494,1524917,"{'#text': '0', 'fulltrack': '0'}","{'name': 'The Marías', 'mbid': '7a3970c9-ecd8-..."
30,Lush Life,201,13071228,1430150,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Zara Larsson', 'mbid': '134e6410-695..."
31,Man I Need,184,8378623,799454,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Olivia Dean', 'mbid': '15e0d608-0869..."
32,BAILE INoLVIDABLE,368,12077532,890771,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Bad Bunny', 'mbid': '89aa5ecb-59ad-4..."
33,Sienna,224,18831623,1129567,"{'#text': '0', 'fulltrack': '0'}","{'name': 'The Marías', 'mbid': '7a3970c9-ecd8-..."
34,The Fate of Ophelia,226,23224001,983584,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Taylor Swift', 'mbid': '20244d07-534..."
35,I Thought I Saw Your Face Today,185,7193593,861597,"{'#text': '0', 'fulltrack': '0'}","{'name': 'She & Him', 'mbid': 'fb821608-35fd-4..."
36,Risk It All,204,1331890,264678,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Bruno Mars', 'mbid': 'afb680f2-b6eb-..."
37,Mr. Brightside,222,49665102,3613294,"{'#text': '0', 'fulltrack': '0'}","{'name': 'The Killers', 'mbid': '95e1ead9-4d31..."
38,Let Down,337,38988682,2457564,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Radiohead', 'mbid': 'a74b1b7f-71a5-4..."
39,Lovers Rock,213,48939403,2125445,"{'#text': '0', 'fulltrack': '0'}","{'name': 'TV Girl', 'mbid': '38f0c7ac-46eb-49c..."
40,Iris,289,30125003,2252486,"{'#text': '0', 'fulltrack': '0'}","{'name': 'The Goo Goo Dolls', 'url': 'https://..."
41,Earrings,0,5741573,470669,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Malcolm Todd', 'mbid': '6c2a79b8-2b5..."
42,See You Again (feat. Kali Uchis),180,55884549,2500761,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Tyler, The Creator', 'mbid': 'f6beac..."
43,Sweater Weather,240,48759891,2909034,"{'#text': '0', 'fulltrack': '0'}","{'name': 'The Neighbourhood', 'mbid': '53b0662..."
44,Dracula - JENNIE remix,209,1931929,313715,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Tame Impala', 'mbid': '63aa26c3-d59b..."
45,Duvet,203,39734193,1933302,"{'#text': '0', 'fulltrack': '0'}","{'name': 'bôa', 'mbid': 'ca1dcba2-792c-4550-ab..."
46,Pain,98,35177185,1867183,"{'#text': '0', 'fulltrack': '0'}","{'name': 'PinkPantheress', 'mbid': '7441014f-f..."
47,E85,0,2429058,326289,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Don Toliver', 'mbid': 'a0723a3c-4135..."
48,Dreams - 2004 Remaster,257,27262904,1931876,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Fleetwood Mac', 'mbid': 'bd13909f-1c..."
49,Pink + White,290,58112597,2394152,"{'#text': '0', 'fulltrack': '0'}","{'name': 'Frank Ocean', 'mbid': 'e520459c-dff4..."

### Filtramos la información que queremos observar

In [8]:
# *Nombre y duración de las canciones
for track in ret.json()["tracks"]["track"]:
  print(track["name"], ". Duracion:", track["duration"],"minutos")

Stateside + Zara Larsson . Duracion: 176 minutos
American Girls . Duracion: 213 minutos
Taste Back . Duracion: 221 minutos
Ready, Steady, Go! . Duracion: 160 minutos
Fame Is a Gun . Duracion: 183 minutos
Aperture . Duracion: 311 minutos
Babydoll . Duracion: 97 minutos
Coming Up Roses . Duracion: 248 minutos
Midnight Sun . Duracion: 189 minutos
Are you listening yet? . Duracion: 192 minutos
POP . Duracion: 216 minutos
Dracula . Duracion: 205 minutos
DtMF . Duracion: 237 minutos
The Waiting Game . Duracion: 169 minutos
Manchild . Duracion: 213 minutos
End of Beginning . Duracion: 159 minutos
Season 2 Weight Loss . Duracion: 229 minutos
Dance No More . Duracion: 194 minutos
Good Luck, Babe! . Duracion: 218 minutos
The Less I Know the Better . Duracion: 234 minutos
So Easy (To Fall In Love) . Duracion: 170 minutos
Carla's Song . Duracion: 253 minutos
WHERE IS MY HUSBAND! . Duracion: 196 minutos
back to friends . Duracion: 199 minutos
Creep . Duracion: 235 minutos
Paint By Numbers . Duracion: 147 minutos
NUEVAYoL . Duracion: 184 minutos
505 . Duracion: 305 minutos
Feel Good Inc. . Duracion: 236 minutos
No One Noticed . Duracion: 236 minutos
Lush Life . Duracion: 201 minutos
Man I Need . Duracion: 184 minutos
BAILE INoLVIDABLE . Duracion: 368 minutos
Sienna . Duracion: 224 minutos
The Fate of Ophelia . Duracion: 226 minutos
I Thought I Saw Your Face Today . Duracion: 185 minutos
Risk It All . Duracion: 204 minutos
Mr. Brightside . Duracion: 222 minutos
Let Down . Duracion: 337 minutos
Lovers Rock . Duracion: 213 minutos
Iris . Duracion: 289 minutos
Earrings . Duracion: 0 minutos
See You Again (feat. Kali Uchis) . Duracion: 180 minutos
Sweater Weather . Duracion: 240 minutos
Dracula - JENNIE remix . Duracion: 209 minutos
Duvet . Duracion: 203 minutos
Pain . Duracion: 98 minutos
E85 . Duracion: 0 minutos
Dreams - 2004 Remaster . Duracion: 257 minutos
Pink + White . Duracion: 290 minutos

#### Comparación de grupos (canciones 'happy'-'sad'):

In [9]:
df_happy = music[music['name'].str.contains('happy',case=False,na=False)]
df_happy.count()

name          0
duration      0
playcount     0
listeners     0
mbid          0
url           0
streamable    0
artist        0
image         0
dtype: int64

In [10]:
df_sad = music[music['name'].str.contains('sad', case=False, na=False)]
df_sad.count()

name          0
duration      0
playcount     0
listeners     0
mbid          0
url           0
streamable    0
artist        0
image         0
dtype: int64

#### Duración promedio de top30 tracks:

In [11]:
# df_top30_duration = music.iloc[:30]
# df_top30_duration
# df_top30_duration.loc[:, 'duration'] = pd.to_numeric(df_top30_duration['duration'], errors='coerce')

# mean = df_top30_duration['duration'].mean()
# mean

### Procedencia de los artisitas top10:

#### Oyentes de los artistas top 10:

In [12]:
# df_top10 = music.head(10)
# df_top10
# df_top10['duration'] = pd.to_numeric(df_top10['duration'], errors='coerce')
# df_top10['listeners'] = pd.to_numeric(df_top10['listeners'], errors='coerce')

# df_top10['artist_name'] = df_top10['artist'].apply(lambda x: x['name'])

# plt.figure(figsize = (15, 5))

# plt.bar(df_top10['artist_name'], df_top10['listeners'], color = ['skyblue'])
# plt.xlabel('Artist name')
# plt.ylabel('Listeners count')
# plt.title("Listener of top 10 artist")
# plt.show()

In [13]:
# Info api request:
ret_artist = requests.get(f"https://ws.audioscrobbler.com/2.0/?method=geo.gettopartists&country=spain&api_key=63e059c3c912a3f642daf2372484d183&format=json")
ret_artist.json()

{'topartists': {'artist': [{'name': 'Bad Bunny',
    'listeners': '13312',
    'mbid': '89aa5ecb-59ad-46f5-b3eb-2d424e941f19',
    'url': 'https://www.last.fm/music/Bad+Bunny',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '1'}},
   {'name': 'ROSALÍA',
    'listeners': '8847',
    'mbid': '25f3abd9-63b5-471a-bd25-feb9672dfa11',
    'url': 'https://www.last.fm/music/ROSAL%C3%8DA',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '2'}},
   {'name': 'Bad Gyal',
    'listeners': '8632',
    'mbid': '9cb2e99f-d0ba-4aa5-a371-0006b0d34090',
    'url': 'https://www.last.fm/music/Bad+Gyal',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '3'}},
   {'name': 'Taylor Swift',
    'listeners': '8578',
    'mbid': '20244d07-534f-4eff-b4d4-930878889970',
    'url': 'https://www.last.fm/music/Taylor+Swift',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '4'}},
   {'name': 'Charli xcx',
    'listeners': '8114',
    'mbid': '260b6184-8828-48eb-945c-bc4cb6fc34ca',
    'url': 'https://www.last.fm/music/Charli+xcx',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '5'}},
   {'name': 'PinkPantheress',
    'listeners': '7776',
    'mbid': '7441014f-f8f5-494f-81db-ff166fbc078d',
    'url': 'https://www.last.fm/music/PinkPantheress',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '6'}},
   {'name': 'Harry Styles',
    'listeners': '7413',
    'mbid': '7eb1ce54-a355-41f9-8d68-e018b096d427',
    'url': 'https://www.last.fm/music/Harry+Styles',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '7'}},
   {'name': 'Lady Gaga',
    'listeners': '7307',
    'mbid': '650e7db6-b795-4eb5-a702-5ea2fc46c848',
    'url': 'https://www.last.fm/music/Lady+Gaga',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '8'}},
   {'name': 'Rihanna',
    'listeners': '6875',
    'mbid': '73e5e69d-3554-40d8-8516-00cb38737a1c',
    'url': 'https://www.last.fm/music/Rihanna',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '9'}},
   {'name': 'Sabrina Carpenter',
    'listeners': '6841',
    'mbid': '1882fe91-cdd9-49c9-9956-8e06a3810bd4',
    'url': 'https://www.last.fm/music/Sabrina+Carpenter',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '10'}},
   {'name': 'Ariana Grande',
    'listeners': '6672',
    'mbid': 'f4fdbb4c-e4b7-47a0-b83b-d91bbfcfa387',
    'url': 'https://www.last.fm/music/Ariana+Grande',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '11'}},
   {'name': 'Quevedo',
    'listeners': '6541',
    'mbid': 'ef9bb29f-f466-4e28-8064-32558f4bb2df',
    'url': 'https://www.last.fm/music/Quevedo',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '12'}},
   {'name': 'Lana Del Rey',
    'listeners': '6167',
    'mbid': 'b7539c32-53e7-4908-bda3-81449c367da6',
    'url': 'https://www.last.fm/music/Lana+Del+Rey',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '13'}},
   {'name': 'The Weeknd',
    'listeners': '6136',
    'mbid': 'c8b03190-306c-4120-bb0b-6f2ebfc06ea9',
    'url': 'https://www.last.fm/music/The+Weeknd',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '14'}},
   {'name': 'C. Tangana',
    'listeners': '6043',
    'mbid': '46d3689c-23e6-46f7-8ad6-c12f13ac9dea',
    'url': 'https://www.last.fm/music/C.+Tangana',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '15'}},
   {'name': 'Rauw Alejandro',
    'listeners': '5865',
    'mbid': '197b70c7-8910-4030-ad03-632d82aa40e3',
    'url': 'https://www.last.fm/music/Rauw+Alejandro',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '16'}},
   {'name': 'Radiohead',
    'listeners': '5634',
    'mbid': 'a74b1b7f-71a5-4011-9441-d0b5e4122711',
    'url': 'https://www.last.fm/music/Radiohead',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '17'}},
   {'name': 'Billie Eilish',
    'listeners': '5627',
    'mbid': 'f4abc0b5-3f7a-4eff-8f78-ac078dbce533',
    'url': 'https://www.last.fm/music/Billie+Eilish',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '18'}},
   {'name': 'Kanye West',
    'listeners': '5626',
    'url': 'https://www.last.fm/music/Kanye+West',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '19'}},
   {'name': 'Tame Impala',
    'listeners': '5554',
    'mbid': '63aa26c3-d59b-4da4-84ac-716b54f1ef4d',
    'url': 'https://www.last.fm/music/Tame+Impala',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '20'}},
   {'name': 'Bruno Mars',
    'listeners': '5530',
    'mbid': 'afb680f2-b6eb-4cd7-a70b-a63b25c763d5',
    'url': 'https://www.last.fm/music/Bruno+Mars',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '21'}},
   {'name': 'Aitana',
    'listeners': '5381',
    'mbid': 'a24f2bd3-0d1b-4c03-8d91-6297ab5a2811',
    'url': 'https://www.last.fm/music/Aitana',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '22'}},
   {'name': 'Rusowsky',
    'listeners': '5353',
    'mbid': 'd836bdef-52ef-4142-baba-573e5b529478',
    'url': 'https://www.last.fm/music/Rusowsky',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'}],
    '@attr': {'rank': '23'}},
   {'name': 'Arctic Monkeys',
    'listeners': '5316',
    'mbid': 'ada7a83c-e3e1-40f1-93f9-3e73dbc9298a',
    'url': 'https://www.last.fm/music/Arctic+Monkeys',
    'streamable': '0',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},

In [14]:
artists_country = pd.DataFrame(ret_artist.json()["topartists"]["artist"])
artists_country.head()

,name,listeners,mbid,url,streamable,image,@attr
0,Bad Bunny,13312,89aa5ecb-59ad-46f5-b3eb-2d424e941f19,https://www.last.fm/music/Bad+Bunny,0,[{'#text': 'https://lastfm.freetls.fastly.net/...,{'rank': '1'}
1,ROSALÍA,8847,25f3abd9-63b5-471a-bd25-feb9672dfa11,https://www.last.fm/music/ROSAL%C3%8DA,0,[{'#text': 'https://lastfm.freetls.fastly.net/...,{'rank': '2'}
2,Bad Gyal,8632,9cb2e99f-d0ba-4aa5-a371-0006b0d34090,https://www.last.fm/music/Bad+Gyal,0,[{'#text': 'https://lastfm.freetls.fastly.net/...,{'rank': '3'}
3,Taylor Swift,8578,20244d07-534f-4eff-b4d4-930878889970,https://www.last.fm/music/Taylor+Swift,0,[{'#text': 'https://lastfm.freetls.fastly.net/...,{'rank': '4'}
4,Charli xcx,8114,260b6184-8828-48eb-945c-bc4cb6fc34ca,https://www.last.fm/music/Charli+xcx,0,[{'#text': 'https://lastfm.freetls.fastly.net/...,{'rank': '5'}

## Géneros musicales en tendencia global

In [ ]:

def get_trending_tags(api_key):
    url = f"https://ws.audioscrobbler.com/2.0/?method=tag.getTopTags&api_key={api_key}&format=json"
    response = requests.get(url)
    return response.json()['toptags']['tag']

api_key = '63e059c3c912a3f642daf2372484d183'
get_trending_tags(api_key)

[{'name': 'rock', 'count': 4069179, 'reach': 402894},
 {'name': 'electronic', 'count': 2498588, 'reach': 262197},
 {'name': 'seen live', 'count': 2194457, 'reach': 82557},
 {'name': 'alternative', 'count': 2130883, 'reach': 267196},
 {'name': 'pop', 'count': 2082364, 'reach': 233753},
 {'name': 'indie', 'count': 2065319, 'reach': 260434},
 {'name': 'female vocalists', 'count': 1634464, 'reach': 169157},
 {'name': 'metal', 'count': 1305603, 'reach': 159014},
 {'name': 'alternative rock', 'count': 1230035, 'reach': 170245},
 {'name': 'jazz', 'count': 1196398, 'reach': 149971},
 {'name': 'classic rock', 'count': 1149319, 'reach': 137113},
 {'name': 'ambient', 'count': 1125319, 'reach': 150168},
 {'name': 'experimental', 'count': 1111930, 'reach': 145396},
 {'name': 'folk', 'count': 958583, 'reach': 151351},
 {'name': 'indie rock', 'count': 928822, 'reach': 137423},
 {'name': 'punk', 'count': 919655, 'reach': 145492},
 {'name': 'Hip-Hop', 'count': 919195, 'reach': 131432},
 {'name': 'hard rock', 'count': 913914, 'reach': 115308},
 {'name': 'black metal', 'count': 905766, 'reach': 64553},
 {'name': 'instrumental', 'count': 888765, 'reach': 126134},
 {'name': 'singer-songwriter', 'count': 857796, 'reach': 110032},
 {'name': 'dance', 'count': 820676, 'reach': 134406},
 {'name': '80s', 'count': 797548, 'reach': 100663},
 {'name': 'death metal', 'count': 761338, 'reach': 72937},
 {'name': 'Progressive rock', 'count': 755130, 'reach': 96774},
 {'name': 'heavy metal', 'count': 751423, 'reach': 90882},
 {'name': 'hardcore', 'count': 722002, 'reach': 99585},
 {'name': 'british', 'count': 700301, 'reach': 93545},
 {'name': 'soul', 'count': 695563, 'reach': 102127},
 {'name': 'chillout', 'count': 652644, 'reach': 103613},
 {'name': 'electronica', 'count': 638894, 'reach': 102538},
 {'name': 'rap', 'count': 626663, 'reach': 110936},
 {'name': 'industrial', 'count': 586017, 'reach': 85133},
 {'name': 'punk rock', 'count': 581839, 'reach': 98427},
 {'name': 'Classical', 'count': 580337, 'reach': 74929},
 {'name': 'Soundtrack', 'count': 577346, 'reach': 85844},
 {'name': 'blues', 'count': 555922, 'reach': 96448},
 {'name': 'thrash metal', 'count': 525770, 'reach': 62951},
 {'name': '90s', 'count': 500775, 'reach': 57169},
 {'name': 'metalcore', 'count': 500360, 'reach': 68526},
 {'name': 'psychedelic', 'count': 487155, 'reach': 78661},
 {'name': 'bookmark', 'count': 486023, 'reach': 177},
 {'name': 'acoustic', 'count': 485858, 'reach': 111786},
 {'name': 'japanese', 'count': 480125, 'reach': 50312},
 {'name': 'hip hop', 'count': 465441, 'reach': 80541},
 {'name': 'post-rock', 'count': 458809, 'reach': 66242},
 {'name': 'Progressive metal', 'count': 454487, 'reach': 62907},
 {'name': 'House', 'count': 452612, 'reach': 74936},
 {'name': 'german', 'count': 446974, 'reach': 59864},
 {'name': 'techno', 'count': 446786, 'reach': 72535}]

In [23]:
ret_generes = get_trending_tags(api_key)
top_generes = pd.DataFrame([ret_generes['name']['count']['reach']])
top_generes.head()

TypeError: list indices must be integers or slices, not str

## **2. Fraude en streams:**

Se usan los datos de Last.fm API también.

OBjetivo: Analizar el comportamiento de los usuarios para detectar anomalias. A través de la informaticón de timestamps y time_between_streams de podría averiguar si esa cuenta ussuario es un humano o un bot.

### Obtener el historial de un usuario para revisar anomalías

In [ ]:
# api_key = '63e059c3c912a3f642daf2372484d183'
# username = ''
# def check_user_activity(api_key, username):
#     url = f"https://ws.audioscrobbler.com/2.0/?method=user.getRecentTracks&user={username}&api_key={api_key}&format=json"
#     data = requests.get(url).json()
#     # Aquí podrías calcular la diferencia de tiempo entre tracks (feature engineering) [5]
#     return data['recenttracks']['track']


**NOTAS**

* Pipeline:

stream logs
↓
feature engineering
↓
EDA
↓
anomaly detection
↓
fraud score

* Modelo  ML debe buscar patrones como: 1000 streams, desde 1 usuario, en 1 hora, duración promedio 5 segundos

## **3. Detector de copyright usando IA (Music Information Retrieval (MIR)):**

Freesound proporciona descriptores de audio precomputados:

. Puedes obtener datos técnicos como: 

* MFCC (Mel-frequency cepstrum coefficients): Esenciales para la identificación de timbres

* Vectores de similitud (como LAION-CLAP): Diseñados para capturar propiedades acústicas y semánticas, ideales para sistemas de huella digital (audio fingerprinting)

. Análisis espectral: Incluye centroide espectral, complejidad y energía, que sirven para crear los espectrogramas que mencionas

Objetivo: Sound Analysis: 

1. En lugar de procesar el audio tú mismo desde cero, solicita directamente los descriptores mfcc, spectral_centroid y rhythm.bpm
2. Web Audio API: Úsala en el frontend de tu plataforma para que cuando el usuario suba una canción se genere el espectrograma visual

In [ ]:
# sound_id = 
# token = 
# def get_sound_features(sound_id, token):
#     # Solicitamos MFCC para el timbre y Spectral Centroid para el brillo [9, 10]
#     url = f"https://freesound.org/apiv2/sounds/{sound_id}/analysis/"
#     headers = {'Authorization': f'Token {token}'}
#     params = {'fields': 'mfcc,spectral_centroid,rhythm.bpm'}
    
#     response = requests.get(url, headers=headers, params=params)
#     return response.json()